export const CORE_RESOURCES = [


  "https://ufodap.com/",
  "https://www.ufoinsight.com/",
  "https://ufopanel.com/",
  "https://ufoquotes.com/",
  "http://www.ufostalker.com/",
  "http://ufotheater.com/",
  "https://ufotimeline.com/",
  "https://uap.guide/",
  "https://ufosint.gitbook.io/hackers/",
  "https://ufodisclosureweb.github.io/starterkit/",
  "https://thedebrief.org/category/uap/",
  "https://www.uapexpedition.org/",
  "https://www.uaptracker.org/",
  "http://ufoevidence.org/",
  "https://www.uapmedia.uk/",
  "https://uap.gg/",
  "https://ufoquotes.com/",
  "https://ufopanel.com/",
  "https://ufodap.com/",
  "https://www.ufoconnector.com/",
  "https://www.ufocasebook.com/",
  "https://www.uaptheory.com/",
  "https://uap-primer.com/",
  "https://www.theufochronicles.com/",
  "https://www.theblackvault.com/documentarchive/",
  "https://the5observables.com/",
  "https://sacred-texts.com/ufo/timeline.htm",
  "https://www.disclosurediaries.com/",
  "https://anomalien.com/",
  "https://www.abovetopsecret.com/index.php",
  "https://ufos-scientificresearch.blogspot.com/search/label/Bigelow",
  "http://localhost:6006/?path=/story/documents-casefilefolder--minimal-case&globals=viewport:desktop",
  "https://ovniologia.com.br/pt/2024/08/pesquisa-mostra-qual-a-visao-dos-academicos-frente-ao-fenomeno-uap.html",


]