declare module 'howler'
declare module 'troika-3d'
declare module 'troika-3d-ui'
declare module 'd3-timer'
declare module 'd3-force'
declare module 'd3-hierarchy'
declare module 'd3-quadtree'
declare module 'split-type'
// declare module '@copilotkit/runtime'
declare module 'animejs'
declare module 'chroma-js'
declare module '@trigger.dev/sdk/v3'