/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/ufo_flying_saucer_spaceship_ovni/scene.gltf --transform 
Files: ./public/assets/ufo_flying_saucer_spaceship_ovni/scene.gltf [15.37KB] > /Users/liamellis/Desktop/ultraterrestrial/apps/app/scene-transformed.glb [1.82MB] (-11768%)
Author: BlackHawk0512 (https://sketchfab.com/BlackHawk0512)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/ufo-flying-saucer-spaceship-ovni-094ce2baf6ee40aa8f083b7d0fcf0a9f
Title: UFO Flying Saucer Spaceship OVNI
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.UFO_Ventanilla_0.geometry} material={materials.Ventanilla} scale={0.01} />
      <mesh geometry={nodes.UFO_UFO_Metal_0.geometry} material={materials.UFO_Metal} scale={0.01} />
      <mesh geometry={nodes.UFO_UFO_BLACK_0.geometry} material={materials.UFO_BLACK} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
