// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "topics",
    columns: [
      { name: "name", type: "string" },
      { name: "summary", type: "text" },
      { name: "photo", type: "file", file: { defaultPublicAccess: true } },
      {
        name: "photos",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
      { name: "title", type: "string", unique: true },
    ],
    revLinks: [
      { column: "topic", table: "topic-subject-matter-experts" },
      { column: "topic", table: "topics-testimonies" },
      { column: "topic", table: "event-topic-subject-matter-experts" },
      { column: "topic", table: "user-saved-topics" },
    ],
  },
  {
    name: "personnel",
    columns: [
      { name: "bio", type: "text" },
      { name: "role", type: "string" },
      { name: "photo", type: "file[]" },
      { name: "rank", type: "int" },
      { name: "credibility", type: "int" },
      { name: "popularity", type: "int" },
      { name: "name", type: "string", unique: true },
      { name: "authority", type: "int" },
    ],
    revLinks: [
      { column: "member", table: "organization-members" },
      {
        column: "subject-matter-expert",
        table: "event-subject-matter-experts",
      },
      {
        column: "subject-matter-expert",
        table: "topic-subject-matter-experts",
      },
      { column: "witness", table: "testimonies" },
      {
        column: "subject-matter-expert",
        table: "event-topic-subject-matter-experts",
      },
      { column: "key-figure", table: "user-saved-key-figure" },
      { column: "author", table: "documents" },
    ],
  },
  {
    name: "events",
    columns: [
      { name: "name", type: "text" },
      { name: "description", type: "text" },
      { name: "location", type: "string" },
      { name: "latitude", type: "float" },
      { name: "longitude", type: "float" },
      { name: "date", type: "datetime" },
      { name: "photos", type: "file[]" },
      { name: "metadata", type: "json", defaultValue: "{}" },
      { name: "title", type: "string", unique: true },
      { name: "summary", type: "text" },
      { name: "category", type: "multiple" },
    ],
    revLinks: [
      { column: "event", table: "event-subject-matter-experts" },
      { column: "event", table: "testimonies" },
      { column: "event", table: "event-topic-subject-matter-experts" },
      { column: "event", table: "user-saved-events" },
    ],
  },
  {
    name: "organizations",
    columns: [
      { name: "name", type: "string" },
      { name: "specialization", type: "string" },
      { name: "description", type: "text" },
      { name: "photo", type: "text" },
      { name: "image", type: "file", file: { defaultPublicAccess: true } },
      { name: "title", type: "string", unique: true },
    ],
    revLinks: [
      { column: "organization", table: "organization-members" },
      { column: "organization", table: "testimonies" },
      { column: "organization", table: "user-saved-organizations" },
      { column: "organization", table: "documents" },
    ],
  },
  {
    name: "sightings",
    columns: [
      { name: "date", type: "datetime" },
      { name: "description", type: "string" },
      { name: "media_link", type: "string" },
      { name: "city", type: "string" },
      { name: "state", type: "string" },
      { name: "country", type: "string" },
      { name: "shape", type: "string" },
      { name: "duration_seconds", type: "string" },
      { name: "duration_hours_min", type: "string" },
      { name: "comments", type: "string" },
      { name: "date_posted", type: "datetime" },
      { name: "latitude", type: "float" },
      { name: "longitude", type: "float" },
    ],
    revLinks: [{ column: "sighting", table: "user-saved-sightings" }],
  },
  {
    name: "event-subject-matter-experts",
    columns: [
      { name: "event", type: "link", link: { table: "events" } },
      {
        name: "subject-matter-expert",
        type: "link",
        link: { table: "personnel" },
      },
    ],
  },
  {
    name: "topic-subject-matter-experts",
    columns: [
      { name: "topic", type: "link", link: { table: "topics" } },
      {
        name: "subject-matter-expert",
        type: "link",
        link: { table: "personnel" },
      },
    ],
  },
  {
    name: "organization-members",
    columns: [
      { name: "member", type: "link", link: { table: "personnel" } },
      { name: "organization", type: "link", link: { table: "organizations" } },
    ],
  },
  {
    name: "testimonies",
    columns: [
      { name: "claim", type: "text" },
      { name: "event", type: "link", link: { table: "events" } },
      { name: "summary", type: "text" },
      { name: "witness", type: "link", link: { table: "personnel" } },
      { name: "documentation", type: "file[]" },
      { name: "date", type: "datetime" },
      { name: "organization", type: "link", link: { table: "organizations" } },
      { name: "source", type: "text" },
      {
        name: "media",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
      { name: "context", type: "text" },
    ],
    revLinks: [
      { column: "testimony", table: "topics-testimonies" },
      { column: "testimony", table: "user-saved-testimonies" },
    ],
  },
  {
    name: "topics-testimonies",
    columns: [
      { name: "topic", type: "link", link: { table: "topics" } },
      { name: "testimony", type: "link", link: { table: "testimonies" } },
    ],
  },
  {
    name: "documents",
    columns: [
      { name: "file", type: "file[]" },
      { name: "summary", type: "text" },
      { name: "embedding", type: "vector", vector: { dimension: 1536 } },
      { name: "title", type: "string" },
      { name: "date", type: "datetime" },
      { name: "author", type: "link", link: { table: "personnel" } },
      { name: "organization", type: "link", link: { table: "organizations" } },
      { name: "url", type: "text" },
      { name: "metadata", type: "json" },
      {
        name: "images",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
    ],
    revLinks: [{ column: "document", table: "user-saved-documents" }],
  },
  {
    name: "locations",
    columns: [
      { name: "name", type: "string" },
      { name: "coordinates", type: "string" },
      { name: "google-maps-location-id", type: "text" },
      { name: "city", type: "string" },
      { name: "state", type: "string" },
      { name: "latitude", type: "float" },
      { name: "longitude", type: "float" },
    ],
  },
  {
    name: "event-topic-subject-matter-experts",
    columns: [
      { name: "event", type: "link", link: { table: "events" } },
      { name: "topic", type: "link", link: { table: "topics" } },
      {
        name: "subject-matter-expert",
        type: "link",
        link: { table: "personnel" },
      },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "email", type: "email", unique: true },
      { name: "name", type: "string" },
      { name: "photo", type: "file", file: { defaultPublicAccess: true } },
      { name: "profile_image_url", type: "string" },
      { name: "external_id", type: "string" },
    ],
    revLinks: [
      { column: "user", table: "user-saved-events" },
      { column: "user", table: "user-saved-topics" },
      { column: "user", table: "user-saved-key-figure" },
      { column: "user", table: "user-saved-testimonies" },
      { column: "user", table: "user-saved-documents" },
      { column: "user", table: "user-theories" },
      { column: "user", table: "user-saved-organizations" },
      { column: "user", table: "user-saved-sightings" },
      { column: "user", table: "mindmaps" },
    ],
  },
  {
    name: "user-saved-events",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "event", type: "link", link: { table: "events" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  {
    name: "user-saved-topics",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "topic", type: "link", link: { table: "topics" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  {
    name: "user-saved-key-figure",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "key-figure", type: "link", link: { table: "personnel" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  {
    name: "user-saved-testimonies",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "testimony", type: "link", link: { table: "testimonies" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  {
    name: "user-saved-documents",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "document", type: "link", link: { table: "documents" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  {
    name: "user-theories",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "name", type: "string" },
      { name: "content", type: "text" },
      { name: "synopsis", type: "text" },
      {
        name: "diagrams",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
    ],
    revLinks: [
      { column: "theory", table: "user-saved-sightings" },
      { column: "theory", table: "user-saved-testimonies" },
      { column: "theory", table: "user-saved-topics" },
      { column: "theory", table: "user-saved-key-figure" },
      { column: "theory", table: "user-saved-organizations" },
      { column: "theory", table: "user-saved-events" },
      { column: "theory", table: "user-saved-documents" },
    ],
  },
  {
    name: "user-saved-organizations",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "organization", type: "link", link: { table: "organizations" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  {
    name: "user-saved-sightings",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "sighting", type: "link", link: { table: "sightings" } },
      { name: "theory", type: "link", link: { table: "user-theories" } },
      { name: "note", type: "text" },
      { name: "note-title", type: "string" },
    ],
  },
  { name: "tags", columns: [] },
  { name: "theories", columns: [] },
  {
    name: "mindmaps",
    columns: [
      { name: "json", type: "json", defaultValue: "{}" },
      { name: "embedding", type: "vector", vector: { dimension: 1536 } },
      { name: "user", type: "link", link: { table: "users" } },
      { name: "file", type: "file", file: { defaultPublicAccess: true } },
    ],
  },
  {
    name: "artifacts",
    columns: [
      { name: "name", type: "string", unique: true },
      { name: "description", type: "text" },
      { name: "photos", type: "multiple" },
      { name: "date", type: "string" },
      { name: "source", type: "text" },
      { name: "origin", type: "text" },
      {
        name: "images",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
    ],
  },
  { name: "case-files", columns: [] },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Topics = InferredTypes["topics"];
export type TopicsRecord = Topics & XataRecord;

export type Personnel = InferredTypes["personnel"];
export type PersonnelRecord = Personnel & XataRecord;

export type Events = InferredTypes["events"];
export type EventsRecord = Events & XataRecord;

export type Organizations = InferredTypes["organizations"];
export type OrganizationsRecord = Organizations & XataRecord;

export type Sightings = InferredTypes["sightings"];
export type SightingsRecord = Sightings & XataRecord;

export type EventSubjectMatterExperts =
  InferredTypes["event-subject-matter-experts"];
export type EventSubjectMatterExpertsRecord = EventSubjectMatterExperts &
  XataRecord;

export type TopicSubjectMatterExperts =
  InferredTypes["topic-subject-matter-experts"];
export type TopicSubjectMatterExpertsRecord = TopicSubjectMatterExperts &
  XataRecord;

export type OrganizationMembers = InferredTypes["organization-members"];
export type OrganizationMembersRecord = OrganizationMembers & XataRecord;

export type Testimonies = InferredTypes["testimonies"];
export type TestimoniesRecord = Testimonies & XataRecord;

export type TopicsTestimonies = InferredTypes["topics-testimonies"];
export type TopicsTestimoniesRecord = TopicsTestimonies & XataRecord;

export type Documents = InferredTypes["documents"];
export type DocumentsRecord = Documents & XataRecord;

export type Locations = InferredTypes["locations"];
export type LocationsRecord = Locations & XataRecord;

export type EventTopicSubjectMatterExperts =
  InferredTypes["event-topic-subject-matter-experts"];
export type EventTopicSubjectMatterExpertsRecord =
  EventTopicSubjectMatterExperts & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type UserSavedEvents = InferredTypes["user-saved-events"];
export type UserSavedEventsRecord = UserSavedEvents & XataRecord;

export type UserSavedTopics = InferredTypes["user-saved-topics"];
export type UserSavedTopicsRecord = UserSavedTopics & XataRecord;

export type UserSavedKeyFigure = InferredTypes["user-saved-key-figure"];
export type UserSavedKeyFigureRecord = UserSavedKeyFigure & XataRecord;

export type UserSavedTestimonies = InferredTypes["user-saved-testimonies"];
export type UserSavedTestimoniesRecord = UserSavedTestimonies & XataRecord;

export type UserSavedDocuments = InferredTypes["user-saved-documents"];
export type UserSavedDocumentsRecord = UserSavedDocuments & XataRecord;

export type UserTheories = InferredTypes["user-theories"];
export type UserTheoriesRecord = UserTheories & XataRecord;

export type UserSavedOrganizations = InferredTypes["user-saved-organizations"];
export type UserSavedOrganizationsRecord = UserSavedOrganizations & XataRecord;

export type UserSavedSightings = InferredTypes["user-saved-sightings"];
export type UserSavedSightingsRecord = UserSavedSightings & XataRecord;

export type Tags = InferredTypes["tags"];
export type TagsRecord = Tags & XataRecord;

export type Theories = InferredTypes["theories"];
export type TheoriesRecord = Theories & XataRecord;

export type Mindmaps = InferredTypes["mindmaps"];
export type MindmapsRecord = Mindmaps & XataRecord;

export type Artifacts = InferredTypes["artifacts"];
export type ArtifactsRecord = Artifacts & XataRecord;

export type CaseFiles = InferredTypes["case-files"];
export type CaseFilesRecord = CaseFiles & XataRecord;

export type DatabaseSchema = {
  topics: TopicsRecord;
  personnel: PersonnelRecord;
  events: EventsRecord;
  organizations: OrganizationsRecord;
  sightings: SightingsRecord;
  "event-subject-matter-experts": EventSubjectMatterExpertsRecord;
  "topic-subject-matter-experts": TopicSubjectMatterExpertsRecord;
  "organization-members": OrganizationMembersRecord;
  testimonies: TestimoniesRecord;
  "topics-testimonies": TopicsTestimoniesRecord;
  documents: DocumentsRecord;
  locations: LocationsRecord;
  "event-topic-subject-matter-experts": EventTopicSubjectMatterExpertsRecord;
  users: UsersRecord;
  "user-saved-events": UserSavedEventsRecord;
  "user-saved-topics": UserSavedTopicsRecord;
  "user-saved-key-figure": UserSavedKeyFigureRecord;
  "user-saved-testimonies": UserSavedTestimoniesRecord;
  "user-saved-documents": UserSavedDocumentsRecord;
  "user-theories": UserTheoriesRecord;
  "user-saved-organizations": UserSavedOrganizationsRecord;
  "user-saved-sightings": UserSavedSightingsRecord;
  tags: TagsRecord;
  theories: TheoriesRecord;
  mindmaps: MindmapsRecord;
  artifacts: ArtifactsRecord;
  "case-files": CaseFilesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://UltraTerrestrial-kgubvq.us-east-1.xata.sh/db/ultraterrestrial",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
