#!/usr/bin/env python3
"""
Demo script showing integration of Charm CLI tools with Disclosure RAG agents.
Run this to see the enhanced CLI in action.
"""

import subprocess
import sys
from pathlib import Path

# Add the current directory to the path so we can import local modules
sys.path.insert(0, str(Path(__file__).parent))

from cli import CharmCLI, DisclosureRAGCLI

def check_charm_tools():
    """Check and display status of Charm CLI tools."""
    charm = CharmCLI()
    
    print("🛸 Disclosure RAG + Charm CLI Tools Demo")
    print("=" * 50)
    
    print("\n📋 Tool Availability Check:")
    for tool, available in charm.available_tools.items():
        status = "✅ Available" if available else "❌ Not found"
        print(f"  {tool}: {status}")
    
    if not any(charm.available_tools.values()):
        print("\n⚠️  No Charm tools found. Install them with:")
        print("   brew install gum huh glow glamour")
        print("   or")
        print("   go install github.com/charmbracelet/[tool]@latest")
        return False
    
    return True

def demo_gum_features():
    """Demonstrate gum features."""
    charm = CharmCLI()
    
    if not charm.available_tools.get('gum', False):
        print("\n⏭️  Skipping gum demo (not installed)")
        return
    
    print("\n🎯 Gum Interactive Demo")
    print("-" * 30)
    
    # Input demo
    name = charm.gum_input("What's your name?", placeholder="Enter your name")
    print(f"Hello, {name}!")
    
    # Choice demo
    research_areas = [
        "Government Disclosure",
        "Historical Cases", 
        "Witness Testimonies",
        "Scientific Analysis"
    ]
    
    interest = charm.gum_choose("What UFO/UAP research area interests you?", research_areas)
    print(f"Great choice! {interest} is a fascinating area.")
    
    # Confirmation demo
    wants_more = charm.gum_confirm("Would you like to see more features?")
    if wants_more:
        print("Excellent! Let's continue...")
    else:
        print("No problem, thanks for trying the demo!")

def demo_markdown_rendering():
    """Demonstrate glow/glamour markdown rendering."""
    charm = CharmCLI()
    
    sample_report = """
# UFO/UAP Research Report

## Executive Summary

This report provides an analysis of recent UFO/UAP developments based on our **Disclosure RAG** system.

## Key Findings

### Government Disclosure
- Pentagon released 3 official videos in 2020
- AATIP program confirmed by DoD
- UAP Task Force established

### Scientific Analysis
- Advanced propulsion systems observed
- Physics-defying maneuvers documented
- Multiple sensor confirmations

### Recommendations

1. **Continue monitoring** official channels
2. **Analyze witness testimonies** systematically  
3. **Cross-reference** historical cases
4. **Engage with** scientific community

---

*Generated by Disclosure RAG CLI*
    """
    
    print("\n📄 Markdown Rendering Demo")
    print("-" * 30)
    
    if charm.available_tools.get('glow', False):
        print("Rendering with Glow:")
        charm.glow_render(sample_report)
    elif charm.available_tools.get('glamour', False):
        print("Rendering with Glamour:")
        rendered = charm.glamour_render(sample_report)
        print(rendered)
    else:
        print("⏭️  No markdown renderers available")
        print("Raw markdown:")
        print(sample_report)

def demo_agent_integration():
    """Demonstrate integration with existing agents."""
    charm = CharmCLI()
    
    print("\n🤖 Agent Integration Demo")
    print("-" * 30)
    
    # Agent selection
    agents = [
        "Claims Evidence Agent",
        "Historical Timeline Agent", 
        "Entity Extraction Agent",
        "Testimony Analysis Agent"
    ]
    
    selected_agent = charm.gum_choose("Select an agent to simulate:", agents)
    
    # Mock query
    query = charm.gum_input(
        f"Enter a query for {selected_agent}",
        placeholder="e.g., Analyze Roswell incident"
    )
    
    # Simulate processing
    print(f"\n🔄 {selected_agent} processing: '{query}'")
    
    # Mock response based on agent type
    if "Claims" in selected_agent:
        response = f"""
## Claims Analysis: {query}

### Evidence Classification
- **Primary Sources**: 3 documents found
- **Witness Testimonies**: 5 accounts analyzed  
- **Physical Evidence**: 2 artifacts referenced
- **Credibility Score**: 7.2/10

### Key Claims Identified
1. Unusual craft observed with advanced propulsion
2. Government knowledge and potential cover-up
3. Physical evidence allegedly recovered

### Verification Status
- ✅ Multiple independent witnesses
- ⚠️  Some claims lack corroborating evidence
- ❌ Official denial vs witness accounts
        """
    elif "Historical" in selected_agent:
        response = f"""
## Historical Timeline: {query}

### Chronological Analysis

**1947-07-08**: Initial incident reported
**1947-07-09**: Military cleanup operation
**1947-07-10**: Official weather balloon explanation
**1978**: First major civilian investigation
**1994**: Military declassification of some records

### Pattern Analysis
- Government response time: 24-48 hours typical
- Media attention peak: 72 hours post-event
- Official explanation timing: Usually within 1 week
        """
    else:
        response = f"""
## Analysis Results: {query}

The {selected_agent} has processed your query and identified several key insights:

- **Confidence Level**: High (87%)
- **Data Sources**: 15 documents analyzed
- **Cross-references**: 8 related cases found
- **Anomalies Detected**: 3 significant patterns

Further analysis recommended for deeper insights.
        """
    
    # Render the response
    charm.glow_render(response)

def main():
    """Main demo function."""
    try:
        # Check if tools are available
        if not check_charm_tools():
            print("\n🚀 You can still run the basic CLI without Charm tools!")
            print("   python cli.py")
            return
        
        print("\n🎉 All set! Here are some demos:")
        
        # Run demos
        demo_gum_features()
        demo_markdown_rendering()
        demo_agent_integration()
        
        print("\n" + "=" * 50)
        print("🚀 Ready to use the full CLI! Run:")
        print("   python cli.py")
        print("   or")
        print("   disclosure-cli")
        
    except KeyboardInterrupt:
        print("\n\n👋 Demo cancelled!")
    except Exception as e:
        print(f"\n❌ Demo error: {e}")

if __name__ == "__main__":
    main()