export { PaperDocument } from './PaperDocument'
export { PaperTexture } from './PaperTexture'
export { SurveyFrame } from './SurveyFrame'
export { ImagePlate } from './ImagePlate'
export { Emblem } from './Emblem'
export { DocHeader } from './DocHeader'
export { DocTitle } from './DocTitle'
export { DocFooter } from './DocFooter'
export { TextColumns } from './TextColumns'
export { PageAccentMark } from './PageAccentMark'
export { Marginalia } from './Marginalia'
export { RedactedText } from './RedactedText'
export { paperDocuments, paperDocumentList } from './documents.data'
