/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/ufo/scene.gltf --transform --output ./converted 
Files: ./public/assets/ufo/scene.gltf [24.13KB] > /Users/liamellis/Desktop/ultraterrestrial/apps/app/scene-transformed.glb [2.1MB] (-8611%)
Author: aung (https://sketchfab.com/aung)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-e9b2edd997284a2aaa0e2bbd2a6a4e85
Title: UFO
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import { Material, Mesh } from 'three'

type UfoModelProps = GroupProps & {
  scale?: number | [number, number, number]
}

type GLTFResult = {
  nodes: {
    Circle001_0: Mesh
    Circle001_1: Mesh
  }
  materials: {
    'Material.001': Material
    'Material.002': Material
  }
}
export function TransformedUfoModel( props: UfoModelProps ) {
  const { nodes, materials } = useGLTF( '@/features/3d/ufos/ufo/scene-transformed.glb' ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001_0.geometry} material={materials['Material.001']} position={[0.227, 2.944, -1.429]} rotation={[-1.082, -0.008, 0]} scale={3.736} />
      <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.002']} position={[0.227, 2.944, -1.429]} rotation={[-1.082, -0.008, 0]} scale={3.736} />
    </group>
  )
}

useGLTF.preload( '@/features/3d/ufos/ufo/scene-transformed.glb' )
