--restrict-filenames
--retry-sleep 1,2,3,5,8,13
--retries infinite
--fragment-retries 100
--file-access-retries 10
--sleep-interval 1
--max-sleep-interval 3
--concurrent-fragments 1
--geo-bypass
--no-call-home
--hls-prefer-ffmpeg
--downloader-args "http:--http-chunk-size=10M" "dash:--http-chunk-size=10M" "m3u8:--http-chunk-size=10M"
--merge-output-format mp4
--output "%(id)s.%(ext)s"
--extractor-args "youtube:player_client=android,web"
--http-header "User-Agent:%(env.YTDLP_USER_AGENT)s"
--http-header "Accept-Language:%(env.YTDLP_ACCEPT_LANGUAGE)s"
