/**
 * Basic Agent Integration for Agentic Chronological Tours
 * Phase 1: Simple agent class that can invoke tools in sequence
 * 
 * Created: July 12, 2025
 * Purpose: Enable AI assistants to control tours through natural language
 */

import type {
  TourNavigationTools,
  ToolExecutionContext,
  NavigateHistoricalTourParams,
  DiscoverRelatedEntitiesParams,
  AnalyzeTemporalContextParams,
  CreateNarrativeBridgeParams,
  SpatialIntelligenceQueryParams
} from '../tools/tour-navigation-tools'
import { HistoricalTourToolsImplementation } from '../tools/tour-tools-implementation'

/**
 * Agent action types for tool orchestration
 */
export type AgentAction = 
  | { type: 'navigate'; params: NavigateHistoricalTourParams }
  | { type: 'discover'; params: DiscoverRelatedEntitiesParams }
  | { type: 'analyze'; params: AnalyzeTemporalContextParams }
  | { type: 'bridge'; params: CreateNarrativeBridgeParams }
  | { type: 'spatial'; params: SpatialIntelligenceQueryParams }
  | { type: 'sequence'; actions: AgentAction[] }
  | { type: 'conditional'; condition: string; ifTrue: AgentAction; ifFalse?: AgentAction }

/**
 * Agent state for tracking exploration progress
 */
export interface AgentState {
  // Current position and context
  currentPosition: {
    tourId: string | null
    waypointIndex: number
    waypointId: string | null
    historicalPeriod: string | null
    year: number | null
  }
  
  // Agent's exploration history
  explorationHistory: {
    visitedWaypoints: string[]
    discoveredEntities: string[]
    analyzedPeriods: Array<{ start: number, end: number }>
    createdBridges: Array<{ from: string, to: string }>
    spatialQueries: string[]
  }
  
  // User interaction context
  userContext: {
    engagementLevel: 'low' | 'medium' | 'high'
    preferredPace: 'fast' | 'normal' | 'slow'
    interestAreas: string[]
    expertiseLevel: 'beginner' | 'intermediate' | 'expert'
    sessionDuration: number // minutes
  }
  
  // Agent's current goals
  currentGoals: {
    primary: string
    secondary: string[]
    autoGenerated: string[]
  }
  
  // Performance tracking
  performance: {
    successfulActions: number
    failedActions: number
    averageActionTime: number
    userSatisfactionScore: number
  }
}

/**
 * Agent execution result for tracking outcomes
 */
export interface AgentExecutionResult {
  success: boolean
  action: AgentAction
  result: any
  duration: number
  nextSuggestedAction?: AgentAction
  userMessage?: string
  errorMessage?: string
}

/**
 * Basic Chronological Tour Agent
 * Provides simple tool orchestration and sequential action execution
 */
export class ChronologicalTourAgent {
  private tools: HistoricalTourToolsImplementation
  private context: ToolExecutionContext
  private state: AgentState
  private isExecuting: boolean = false
  
  constructor(
    tools: HistoricalTourToolsImplementation,
    context: ToolExecutionContext,
    initialState?: Partial<AgentState>
  ) {
    this.tools = tools
    this.context = context
    this.state = this.initializeState(initialState)
  }
  
  /**
   * Execute a single agent action
   */
  async executeAction(action: AgentAction): Promise<AgentExecutionResult> {
    if (this.isExecuting) {
      throw new Error('Agent is already executing an action')
    }
    
    this.isExecuting = true
    const startTime = performance.now()
    
    try {
      let result: any
      
      switch (action.type) {
        case 'navigate':
          result = await this.tools.navigate_historical_tour(action.params)
          this.updateStateAfterNavigation(action.params, result)
          break
          
        case 'discover':
          result = await this.tools.discover_related_entities(action.params)
          this.updateStateAfterDiscovery(action.params, result)
          break
          
        case 'analyze':
          result = await this.tools.analyze_temporal_context(action.params)
          this.updateStateAfterAnalysis(action.params, result)
          break
          
        case 'bridge':
          result = await this.tools.create_narrative_bridge(action.params)
          this.updateStateAfterBridge(action.params, result)
          break
          
        case 'spatial':
          result = await this.tools.spatial_intelligence_query(action.params)
          this.updateStateAfterSpatial(action.params, result)
          break
          
        case 'sequence':
          result = await this.executeActionSequence(action.actions)
          break
          
        case 'conditional':
          result = await this.executeConditionalAction(action)
          break
          
        default:
          throw new Error(`Unknown action type: ${(action as any).type}`)
      }
      
      const endTime = performance.now()
      const duration = endTime - startTime
      
      // Update performance metrics
      this.state.performance.successfulActions++
      this.state.performance.averageActionTime = 
        (this.state.performance.averageActionTime + duration) / 2
      
      // Generate next suggested action
      const nextAction = await this.suggestNextAction(action, result)
      
      const executionResult: AgentExecutionResult = {
        success: true,
        action,
        result,
        duration,
        nextSuggestedAction: nextAction,
        userMessage: this.generateUserMessage(action, result)
      }
      
      this.isExecuting = false
      return executionResult
      
    } catch (error) {
      const endTime = performance.now()
      const duration = endTime - startTime
      
      this.state.performance.failedActions++
      
      const executionResult: AgentExecutionResult = {
        success: false,
        action,
        result: null,
        duration,
        errorMessage: (error as Error).message
      }
      
      this.isExecuting = false
      return executionResult
    }
  }
  
  /**
   * Execute a sequence of actions
   */
  async executeActionSequence(actions: AgentAction[]): Promise<AgentExecutionResult[]> {
    const results: AgentExecutionResult[] = []
    
    for (const action of actions) {
      const result = await this.executeAction(action)
      results.push(result)
      
      // Stop sequence if action fails
      if (!result.success) {
        break
      }
      
      // Brief pause between actions for better UX
      await new Promise(resolve => setTimeout(resolve, 100))
    }
    
    return results
  }
  
  /**
   * Execute conditional action based on current state
   */
  async executeConditionalAction(action: AgentAction & { type: 'conditional' }): Promise<AgentExecutionResult> {
    const conditionMet = await this.evaluateCondition(action.condition)
    const actionToExecute = conditionMet ? action.ifTrue : action.ifFalse
    
    if (!actionToExecute) {
      return {
        success: true,
        action,
        result: { conditionMet, actionTaken: null },
        duration: 0,
        userMessage: `Condition "${action.condition}" was ${conditionMet ? 'met' : 'not met'}, no action taken`
      }
    }
    
    return await this.executeAction(actionToExecute)
  }
  
  /**
   * Get current agent state
   */
  getState(): AgentState {
    return { ...this.state }
  }
  
  /**
   * Update agent state
   */
  updateState(updates: Partial<AgentState>): void {
    this.state = { ...this.state, ...updates }
  }
  
  /**
   * Reset agent to initial state
   */
  reset(newState?: Partial<AgentState>): void {
    this.state = this.initializeState(newState)
  }
  
  /**
   * Generate contextual user message based on action and result
   */
  private generateUserMessage(action: AgentAction, result: any): string {
    switch (action.type) {
      case 'navigate':
        if (result.success) {
          return `Navigated to: ${result.newState.waypointTitle}. ${result.newState.narrative}`
        }
        return `Navigation failed: ${result.message}`
        
      case 'discover':
        if (result.success) {
          return `Discovered ${result.entities.length} related entities. Key findings include connections to ${result.entities.slice(0, 3).map((e: any) => e.title).join(', ')}.`
        }
        return `Entity discovery failed: ${result.message}`
        
      case 'analyze':
        if (result.success) {
          const analysis = result.analysis
          return `Analysis complete for ${analysis.timePeriod.start_year}-${analysis.timePeriod.end_year}. Found ${analysis.significance.keyEvents.length} key events and ${analysis.connections.causalRelationships.length} important relationships.`
        }
        return `Analysis failed: ${result.message}`
        
      case 'bridge':
        if (result.success) {
          return `Created ${result.bridge.bridgeType} bridge from ${result.bridge.fromPeriod} to ${result.bridge.toPeriod}. ${result.bridge.narrative}`
        }
        return `Bridge creation failed: ${result.message}`
        
      case 'spatial':
        if (result.success) {
          return `Spatial analysis revealed ${result.spatialAnalysis.proximityGroups.length} proximity groups and ${result.spatialAnalysis.optimizationSuggestions.length} optimization opportunities.`
        }
        return `Spatial analysis failed: ${result.message}`
        
      default:
        return result.success ? 'Action completed successfully' : `Action failed: ${result.message}`
    }
  }
  
  /**
   * Suggest next action based on current context
   */
  private async suggestNextAction(lastAction: AgentAction, result: any): Promise<AgentAction | undefined> {
    // Simple heuristics for action suggestion
    switch (lastAction.type) {
      case 'navigate':
        if (result.success && this.state.userContext.engagementLevel === 'high') {
          return {
            type: 'discover',
            params: {
              current_context: result.newState.waypointTitle,
              entity_types: ['events', 'personnel'],
              relationship_depth: 1
            }
          }
        }
        break
        
      case 'discover':
        if (result.success && result.entities.length > 5) {
          return {
            type: 'spatial',
            params: {
              query_type: 'clustering',
              target_entities: result.entities.slice(0, 10).map((e: any) => e.id),
              optimization_goal: 'comprehension'
            }
          }
        }
        break
        
      case 'analyze':
        if (result.success && result.analysis.gaps.unexploredConnections.length > 0) {
          return {
            type: 'bridge',
            params: {
              from_period: `${result.analysis.timePeriod.start_year}`,
              to_period: `${result.analysis.timePeriod.end_year + 10}`,
              bridge_type: 'evolution',
              evidence_threshold: 0.6
            }
          }
        }
        break
    }
    
    return undefined
  }
  
  /**
   * Evaluate condition for conditional actions
   */
  private async evaluateCondition(condition: string): Promise<boolean> {
    // Simple condition evaluation - can be expanded
    const currentState = this.tools.getCurrentState()
    
    switch (condition) {
      case 'has_nodes':
        return currentState.nodes.length > 0
      case 'high_engagement':
        return this.state.userContext.engagementLevel === 'high'
      case 'tour_active':
        return currentState.tourId !== null
      case 'spatial_groups_available':
        return currentState.spatialGroups.length > 0
      default:
        console.warn(`Unknown condition: ${condition}`)
        return false
    }
  }
  
  /**
   * Initialize agent state
   */
  private initializeState(partial?: Partial<AgentState>): AgentState {
    const defaultState: AgentState = {
      currentPosition: {
        tourId: null,
        waypointIndex: 0,
        waypointId: null,
        historicalPeriod: null,
        year: null
      },
      explorationHistory: {
        visitedWaypoints: [],
        discoveredEntities: [],
        analyzedPeriods: [],
        createdBridges: [],
        spatialQueries: []
      },
      userContext: {
        engagementLevel: 'medium',
        preferredPace: 'normal',
        interestAreas: [],
        expertiseLevel: 'beginner',
        sessionDuration: 0
      },
      currentGoals: {
        primary: 'Explore UFO/UAP history chronologically',
        secondary: [],
        autoGenerated: []
      },
      performance: {
        successfulActions: 0,
        failedActions: 0,
        averageActionTime: 0,
        userSatisfactionScore: 0.5
      }
    }
    
    return { ...defaultState, ...partial }
  }
  
  /**
   * State update methods for different action types
   */
  private updateStateAfterNavigation(params: NavigateHistoricalTourParams, result: any): void {
    if (result.success) {
      this.state.currentPosition.waypointId = result.newState.currentWaypointId
      this.state.currentPosition.waypointIndex = result.tourContext.currentIndex
      this.state.currentPosition.tourId = result.tourContext.tourId
      
      if (!this.state.explorationHistory.visitedWaypoints.includes(result.newState.currentWaypointId)) {
        this.state.explorationHistory.visitedWaypoints.push(result.newState.currentWaypointId)
      }
      
      if (params.target_year) {
        this.state.currentPosition.year = params.target_year
      }
      
      if (params.target_period) {
        this.state.currentPosition.historicalPeriod = params.target_period
      }
    }
  }
  
  private updateStateAfterDiscovery(params: DiscoverRelatedEntitiesParams, result: any): void {
    if (result.success) {
      const newEntities = result.entities.map((e: any) => e.id).filter(
        (id: string) => !this.state.explorationHistory.discoveredEntities.includes(id)
      )
      this.state.explorationHistory.discoveredEntities.push(...newEntities)
    }
  }
  
  private updateStateAfterAnalysis(params: AnalyzeTemporalContextParams, result: any): void {
    if (result.success) {
      this.state.explorationHistory.analyzedPeriods.push({
        start: params.time_period.start_year,
        end: params.time_period.end_year
      })
    }
  }
  
  private updateStateAfterBridge(params: CreateNarrativeBridgeParams, result: any): void {
    if (result.success) {
      this.state.explorationHistory.createdBridges.push({
        from: params.from_period,
        to: params.to_period
      })
    }
  }
  
  private updateStateAfterSpatial(params: SpatialIntelligenceQueryParams, result: any): void {
    if (result.success) {
      this.state.explorationHistory.spatialQueries.push(params.query_type)
    }
  }
}

/**
 * Factory function for creating agents with different configurations
 */
export function createChronologicalTourAgent(
  tools: HistoricalTourToolsImplementation,
  context: ToolExecutionContext,
  config?: {
    userExpertise?: 'beginner' | 'intermediate' | 'expert'
    preferredPace?: 'fast' | 'normal' | 'slow'
    interestAreas?: string[]
  }
): ChronologicalTourAgent {
  const initialState: Partial<AgentState> = {
    userContext: {
      engagementLevel: 'medium',
      preferredPace: config?.preferredPace || 'normal',
      interestAreas: config?.interestAreas || [],
      expertiseLevel: config?.userExpertise || 'beginner',
      sessionDuration: 0
    }
  }
  
  return new ChronologicalTourAgent(tools, context, initialState)
}

/**
 * Predefined action sequences for common tour patterns
 */
export const PREDEFINED_SEQUENCES = {
  quick_overview: [
    { type: 'navigate' as const, params: { direction: 'jump_to_period' as const, target_period: 'early_sightings' as const, depth_level: 'overview' as const } },
    { type: 'navigate' as const, params: { direction: 'jump_to_period' as const, target_period: 'cold_war' as const, depth_level: 'overview' as const } },
    { type: 'navigate' as const, params: { direction: 'jump_to_period' as const, target_period: 'modern_research' as const, depth_level: 'overview' as const } },
    { type: 'navigate' as const, params: { direction: 'jump_to_period' as const, target_period: 'disclosure_era' as const, depth_level: 'overview' as const } }
  ],
  
  deep_dive_roswell: [
    { type: 'navigate' as const, params: { direction: 'jump_to_year' as const, target_year: 1947, depth_level: 'comprehensive' as const } },
    { type: 'discover' as const, params: { current_context: 'Roswell incident 1947', entity_types: ['events', 'personnel', 'organizations'] as const, relationship_depth: 2 as const } },
    { type: 'analyze' as const, params: { time_period: { start_year: 1947, end_year: 1952 }, analysis_type: 'connections' as const } },
    { type: 'spatial' as const, params: { query_type: 'clustering' as const, optimization_goal: 'comprehension' as const } }
  ],
  
  disclosure_evolution: [
    { type: 'navigate' as const, params: { direction: 'jump_to_period' as const, target_period: 'early_sightings' as const, narrative_focus: 'government_response' } },
    { type: 'bridge' as const, params: { from_period: 'early sightings era', to_period: 'modern disclosure era', bridge_type: 'evolution' as const, evidence_threshold: 0.7 } },
    { type: 'analyze' as const, params: { time_period: { start_year: 1940, end_year: 2024 }, analysis_type: 'progression' as const } }
  ]
}